#! /bin/sh

BW=1
bspc config border_width $BW
bspc config window_gap -$BW
for side in top right bottom left ; do
    bspc config ${side}_padding $BW
done

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

panel &

# NOTE: bspwm panel had additional packages to install
# Optional Deps  : sxhkd: to define keyboard and pointer bindings
#                 xtitle-git: for the example panel
#                 sutils-git: for the example panel
#                 bar-aint-recursive: for the example panel
#                 terminus-font: for the example panel
