#!/bin/bash

FONT_FAMILY='Menlo'
FONT_SIZE=16
FONT="${FONT_FAMILY}:pixelsize=${FONT_SIZE}"

PANEL_HEIGHT=30
SCREEN_WIDTH=2880
DMENU_WIDTH=1600

# PANEL_COLOR='#f19200' #orange
PANEL_COLOR='#2aaf6e' #green
PANEL_URGENT_COLOR='#c55b4e'
PANEL_TEXT_LIGHT='#eeefff'
PANEL_TEXT_DARK='#6b6b6b'
PANEL_BG='#21262e'
PANEL_ICON_DIR="/home/tyler/.config/bspwm/panel/icons"


# PANEL_COLOR='#6ca6ce' #blue
# PANEL_COLOR='#86c797' #green
# PANEL_URGENT_COLOR='#c55b4e'
# PANEL_TEXT_LIGHT='#cccccc'
# PANEL_TEXT_DARK='#6b6b6b'
# PANEL_BG='#1e1e1e'
# PANEL_ICON_DIR="/home/tyler/.config/bspwm/panel/icons"